### ISSUE TITLE
[TYPO] Justificar parágrafos

### ISSUE THREAD

**Issue by patrickmilano** [vuejs-br/vuejs.org#7]
Se possível, justificar os parágrafos redigidos e traduzidos para uma melhor padronização do site!

Valeu!

**Comment by vitorarjol** [comment]
Oi Patrick, tudo bem? Essa tradução está muito defasada! Embora possa dar uma introdução do Vue, eu recomendo utilizar a documentação oficial, que é a http://vuejs.org/. Vou fechar esse tópico por enquanto, pois a tradução não está ativa.

**Comment by patrickmilano** [comment]
Qual o motivo da tradução estar parada? Falta de colaboradores? Estou disponível e interessado em poder contribuir com a transcrição da página!

**Comment by vitorarjol** [comment]
Exatamente @patrickmilano. Eu iniciei a tradução, mas tive de parar, e isso já faz bastante tempo. Minha sugestão é que a tradução seja feita já da versão 2.0, que está sendo documentada nesse momento. Você pode visualizar a versão mais atual aqui: https://github.com/vuejs/vuejs.org/issues/319. Posso lhe ajudar a dar os passos iniciais na tradução se você quiser.
